### ISSUE TITLE
Weather - Poor Fetch

### ISSUE THREAD

**Issue by chriscana** [MetaWatchOpenProjects/MWM-for-iOS-Gen1#4] opened 2012-06-12 19:45 UTC
I believe you are using google weather to pull weather data. Entering Milford or Milford, CT doesnt always pull latest data, sometimes doesn't update at all for hours. Connection to internet and watch is fine, set update to 30min - just seems like buggy updating and fetching.

**Comment by metawatchclient** [comment] 2012-06-13 11:54
Maybe the server data has not been changed during these hours? or your phone do not have Internet access during that period?

**Comment by chriscana** [comment] 2012-06-13 13:11
Server data does change (checked). Watch has internet access. Just seems app does not update properly or at all - typically will go 24 hours or more without ever dating the status or weather icon (stays on "clear" for over 24 hours when it is raining, as an example).

**Comment by chriscana** [comment] 2012-06-13 13:41
For Instance, it has been raining non stop all night (milford, CT or 06460), google says light rain, and my watch has said clear and sunny for hours even though watch is connected, phone is on internet, and google is listing correct as light rain. Fetching just seems broken. Even tried uninstalling and reinstalling app on iphone. Same thing.

**Comment by metawatchclient** [comment] 2012-06-13 13:51
We used this:
http://www.google.com/ig/api?weather=milford, CT

Does your weather never update, or failed to update sometime?

**Comment by chriscana** [comment] 2012-06-13 13:53
Weather app is equal to the watch - stays suck on clear indefinitely even when its raining and google says its been raning for hours and app is set to update every 30min

**Comment by metawatchclient** [comment] 2012-06-13 14:03
I just updated the MWM.

I found a issue which may cause the incorrect weather data displayed... Could you try the new version and give some feedback? Thanks.

**Comment by chriscana** [comment] 2012-06-13 14:12
New version is displaying correct data from google (high/low, weather image and current forecast) - that could have fixed it, just might have been pulling incorrect data! Looks good.

**Comment by metawatchclient** [comment] 2012-06-13 14:23
Let me know if you noticed anything abnormal with the weather again... otherwise I will just close the issue:)

**Comment by chriscana** [comment] 2012-06-13 14:46
It might not be updating the wethaer graphic correct. For instance, it is overcast in Milford, CT right now and the weather icon is a fully bright sun. Temp, description, and hi/lo seem correct

**Comment by metawatchclient** [comment] 2012-06-13 14:47
Yup, it is a known issue... MWM does not have every the bitmap for each weather condition. It will be fixed gradually...

**Comment by chriscana** [comment] 2012-06-14 13:38
Still not working very well. Read overcast for about 24 hors straight (it was overcast).. had to close the app and reconnect to get a weather update to current weather and now the screen just reads NULL with no weather filling in after reboot of app. App doesnt seem to be properly updating watch. Again: Milford, CT weather.

**Comment by metawatchclient** [comment] 2012-06-14 13:39
NULL means the google api is down...

http://www.google.com/ig/api?weather=milford,CT

no such place found... 

maybe you can try using post code?

Update:
I just tried the google api, it seems it is having problems resolving US cites... let's wait for a while to see if the problem can be solved by Google.
Not working:
http://www.google.com/ig/api?weather=dallas
http://www.google.com/ig/api?weather=boston
Working:
http://www.google.com/ig/api?weather=espoo
http://www.google.com/ig/api?weather=beijing

**Comment by chriscana** [comment] 2012-06-15 14:41
Still not fetching correctly. Read 66 degrees for over 10 hours. Disconnecting and reconnecting watch, read the same. Had to physically close and reopen app to get a weather update (should have been 73 degrees). Seems app is not correctly pulling data and seing to watch every 30min, as set. Never does unless I completely close and reopen app.

**Comment by chriscana** [comment] 2012-06-15 17:19
Confirmed twice today that weather did not update in 30min timeframe unless the app was completely shut down and then reopened on the iphone. It will then do an update, otherwise it stays on whatever the last update was.

**Comment by metawatchclient** [comment] 2012-06-16 22:14
ok. it might be something related to the URL cache in the iOS... I will take a look at this still.

**Comment by metawatchclient** [comment] 2012-06-18 14:18
I have added a local notification when weather is updated and also an updated weather engine. Can you try again with the latest code?

**Comment by chriscana** [comment] 2012-06-19 13:36
Seems like weather is properly updating now

**Comment by metawatchclient** [comment] 2012-06-19 16:17
OK. Let's give couple of more days to make sure this is now fixed.

**Comment by jamierytlewski** [comment] 2012-06-25 13:09
I'm running into this issue now. Did not update at all through the night. I had change the zip code to a different one than back to make the weather update.

**Comment by metawatchclient** [comment] 2012-06-25 13:28
This should not reproduce in the latest build. Can you try the latest build again?

**Comment by jamierytlewski** [comment] 2012-06-25 13:31
That was the one I had downloaded...I just downloaded it as of Saturday night.

**Comment by metawatchclient** [comment] 2012-06-25 14:24
Can you try again? It was updated on both Sunday and Monday(Today).

**Comment by jamierytlewski** [comment] 2012-06-26 13:20
I've tried again. I can't see in the code where it's doing the intervals. I have mine setup for every half an hour and it does not update. The notifications do not ever update also. I just recently looked and the last message was an hour ago. Does there need to be some other trigger?

**Comment by metawatchclient** [comment] 2012-06-26 14:33
Can you see MWMCheckEvent in the console output every minute?

**Comment by jamierytlewski** [comment] 2012-06-26 14:53
Just to let you know, I'm not really going to be able to look at it for the next few days. All I know is that when I go to my phone, click on the location, and push done, I get the updates. I tried switching it to every 2 minutes last night (i reverted my changes before this morning) and I was seeing nothing being updated in the console after the initial load.

**Comment by jamierytlewski** [comment] 2012-06-26 14:55
I'm new to iOS programming, but I was just curious as to why the NSTimer is not being used for the intervals?

**Comment by jamierytlewski** [comment] 2012-06-26 17:39
By the way, I can't see the MWMCheckEvent every minute.I downloaded a fresh new copy. And it never hits the NSLog(@"MWMCheckEvent:%d", roundedTimeStamp);

**Comment by metawatchclient** [comment] 2012-06-26 18:52
If you cannot see MWMCheckEvent, then the problem is on the watch side... did you use our latest firmware from the github?

At first we were also using NSTimer, but soon we figured out that NSTimer is not accurate when the app is in the "suspended/background" mode...

**Comment by jamierytlewski** [comment] 2012-06-26 19:25
Using v 3.1.0 fw and 2.0.0 stack. Msp430 rev e

On Tuesday, June 26, 2012, metawatchclient wrote:

> If you cannot see MWMCheckEvent, then the problem is on the watch side...
> did you use our latest firmware from the github?
> 
> At first we were also using NSTimer, but soon we figured out that NSTimer
> is not accurate when the app is in the "suspended/background" mode...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/MetaWatchOpenProjects/MWM-for-iPhone/issues/4#issuecomment-6584531

## 

Jamie R. Rytlewski
jamier.net@gmail.com
http://www.jamier.net

**Comment by jamierytlewski** [comment] 2012-06-27 01:49
Ok, I think it's working now. I received an updated FW. I'm up to 3.1.3 and Stack 2.0.3 now. I'm getting the MWMCheckEvent now and it appears to be getting the updates. The biggest thing is that I'm traveling for the next 10 days and I was hoping to get it to change more often when I'm in different places. 

I updated some code (not on github yet as i want to optimize it), where it takes your location vs having to put the info in manually. Thanks again!

**Comment by metawatchclient** [comment] 2012-06-27 14:24
Fixed.

**Closed as completed by metawatchclient** 2012-06-27 14:24 UTC
Labels: Fixed
